### ISSUE TITLE
CRSP - remove channel feature

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [tazama-lf/event-director#124]
## User Story

**As a** Tazama system operator
**I want** to remove the channel feature
**so that** the system is as simple as possible to maintain and configure for an inexperienced user; and
**so that** the system performs as fast as possible at the lowest possible cost

## Acceptance Criteria
1. Bump the FRMS-coe-lib version
2. Bump the FRMS-coe-startup-lib
3. Network map to be restructured to remove the channel branching
4. The CRSP processing of the network map must change to remove the channel feature

6. Update documentation (migrate CRSP technical documentation from Confluence @Sandy-at-Tazama & @Justus-at-Tazama )
7. Testing: unit, integration, end-to-end, regression see TMS-configuration - remove channel feature [#2](https://github.com/frmscoe/tms-configuration/issues/2)
8. Update documentation as follows:

## Overview
What does the processor do?
## Inputs 
(Docstring documentation)
What does the processor need? 
## Internal process flow 
(diagram, with descriptions)
How does the processor work?
## Outputs 
(linked to diagram exit points)
What does the processor deliver?
## Environment variables
(table)
How can the processor behaviour be configured?
## Deployment
How is the processor deployed?
## Operation
How is the processor operated? (Stopped, Restarted, etc)
## Troubleshooting
What are typical issues and their remedies

**Comment by rtkay123** [comment]
@Sandy-at-Tazama  Working on the docs, being mindful of this current issue: https://github.com/frmscoe/channel-router-setup-processor/issues/129

I see some docs on inputs for [`Pain001`](https://github.com/frmscoe/channel-router-setup-processor#request-for-pain001), currently, as per the linked [issue](https://github.com/frmscoe/channel-router-setup-processor/issues/129), CRSP will not receive that message. Do I keep the docs as is (since the bug will be addressed eventually), or remove it in pursuit of correctness for the docs (specific to messages that aren't Pacs002) to be re-added when the bug has been addressed?

Adding on, I currently have no way to determine the respective outputs of each message as well, since the inputs do not hit the processor.

Affected Inputs/Outputs: `Pain001`, `Pain013` and `Pacs008`

**Comment by Justus-at-Tazama** [comment]
Getting the pacs.002 payload sample is easy because it's basically the same one that we produce when we generate a test payload directly into the CRSP in our Postman tests.

To Rodney's point, the current bug reduces the ingestion of the other payloads to basically the `TxTp` attribute and that's it.

We can pre-emptively fix the payload so that the bug is then a contradiction to the documented and expected behaviour, but to be honest, I am also comfortable just documenting the exact existing functionality and then leaving it to the bug to then fix the docs as well.

@rtkay123 - So let's do that - document the as-is and then we'll update the docs when we fix the bug.

**Comment by Sandy-at-Tazama** [comment]
Abbreviation for Event Director should be "ED" to replace "CRSP"
